# Generated by Django 4.2.1 on 2023-05-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_menuitem_user_alter_booking_id_alter_menu_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
